#!/bin/sh

# Copyright 2016 Michael Schlenstedt, michael@loxberry.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/opt/loxberry/bin:/opt/loxberry/sbin"

. /lib/lsb/init-functions

# Start UPnP Server
log_action_begin_msg "Starting UPNP Server"
if [ -f /opt/loxberry/config/system/minidlna.conf ]
then
  MYIP=$(hostname -I) || true
  if [ "$MYIP" ]; then
    sed -i "s/presentation_url=.*\$/presentation_url=http:\/\/$MYIP/" /opt/loxberry/config/system/minidlna.conf
  fi
fi
if [ -f /opt/loxberry/sbin/minidlnad ] && [ -f /opt/loxberry/config/system/minidlna.conf ]
then
  /opt/loxberry/sbin/minidlnad -f /opt/loxberry/config/system/minidlna.conf
fi

exit 0
