#!/bin/bash

if [ -f /usr/bin/shellinaboxd ]
then
	echo "Start ShellinaBox Terminal"
	pkill -f shellinaboxd
	sleep 1
	/usr/bin/shellinaboxd -b --no-beep --localhost-only -t -n -p 64994 -s "/:loxberry:loxberry:$LBHOMEDIR:/usr/bin/ssh loxberry@localhost" --user-css "Normal:-/etc/shellinabox/options-available/00+Black on White.css,Reverse:+/etc/shellinabox/options-available/00_White On Black.css" --user-css "Color:+/etc/shellinabox/options-available/01+Color Terminal.css,Monochrome:-/etc/shellinabox/options-available/01_Monochrome.css" > /dev/null 2>&1 &
	mkdir -p $LBHOMEDIR/.ssh
	ssh-keyscan -H localhost >> $LBHOMEDIR/.ssh/known_hosts
	chown -R loxberry:loxberry $LBHOMEDIR/.ssh
fi
