#!/bin/sh
#
# Most parts taken from raspi-config. Some adjustment to fit Loxberry's needs.
#
# raspi-config https://github.com/RPi-Distro/raspi-config
# See LICENSE file for copyright and license details
#

if $LBSBIN/showpitype | grep -q "unknown"; then
	echo "This seems not to be a Raspberry. Eciting."
	exit 1
fi

ID=$(id -u)
if [ "$ID" != "0" ] ; then
	echo "This script has to be run as root. Exiting."
	exit 1
fi

CONFIG=/boot/config.txt
CMDLINE=/boot/cmdline.txt

set_config_var() {
  lua - "$1" "$2" "$3" <<EOF > "$3.bak"
local key=assert(arg[1])
local value=assert(arg[2])
local fn=assert(arg[3])
local file=assert(io.open(fn))
local made_change=false
for line in file:lines() do
  if line:match("^#?%s*"..key.."=.*$") then
    line=key.."="..value
    made_change=true
  end
  print(line)
end

if not made_change then
  print(key.."="..value)
end
EOF
mv "$3.bak" "$3"
}

case "$1" in
en_console)
	if grep -q "console=ttyAMA0" $CMDLINE ; then
		if [ -e /proc/device-tree/aliases/serial0 ]; then
			sed -i $CMDLINE -e "s/console=ttyAMA0/console=serial0/"
		fi
	elif ! grep -q "console=ttyAMA0" $CMDLINE && ! grep -q "console=serial0" $CMDLINE ; then
		if [ -e /proc/device-tree/aliases/serial0 ]; then
			sed -i $CMDLINE -e "s/root=/console=serial0,115200 root=/"
		else
			sed -i $CMDLINE -e "s/root=/console=ttyAMA0,115200 root=/"
		fi
	fi
	set_config_var enable_uart 1 $CONFIG
;;

dis_console)
    sed -i $CMDLINE -e "s/console=ttyAMA0,[0-9]\+ //"
    sed -i $CMDLINE -e "s/console=serial0,[0-9]\+ //"
;;

en_uart)
	set_config_var enable_uart 1 $CONFIG
;;

dis_uart)
	set_config_var enable_uart 0 $CONFIG
;;

*)

	echo "Usage: $0 [en_serial|dis_serial|en_sonsole|dis_console]" >&2
	exit 3
	;;

esac
