#!/usr/bin/perl
 # client
 # needed libio-socket-multicast-perl

 use strict;
 use lib "$ENV{'LBHOMEDIR'}/libs/perllib";
 use IO::Socket::Multicast;
 use IO::Socket::INET;
 use DateTime;
 use LoxBerry::System;
 use Config::Simple;
 use Data::UUID;
 use Thread;

 my $cfg;
 if (-e "$lbsconfigdir/general.cfg") {
	$cfg = new Config::Simple("$lbsconfigdir/general.cfg");
 } elsif (-e "$lbsconfigdir/general.cfg.default") {
	$cfg = new Config::Simple("$lbsconfigdir/general.cfg.default");
 }

 if (is_enabled($cfg->param("SSDP.DISABLED"))) { 
	 print "SSDPD is disabled\n";
	 while (1) {
		 sleep 1;
	}
 }
 
 my $s1 = IO::Socket::INET->new(Proto=>'udp');
 our $s2 = IO::Socket::Multicast->new(Proto=>'udp',LocalPort=>1900);
 if (!$s2) {die "Cloud not bind LocalPort";} 
 $s2->mcast_add('239.255.255.250') || die "Could not add multicast group.\n";

 
 my $from = '';
 my $port = 0;
 my $UUID = '';
 if ($cfg->param("SSDP.UUID")) {
	 $UUID = $cfg->param("SSDP.UUID");
 } else {
	 my $u = Data::UUID->new;
	 $UUID = $u->create_str();
	 $cfg->param("SSDP.UUID",$UUID);
	 $cfg->save();
 }
 my $IP = LoxBerry::System::get_localip();
 if (LoxBerry::System::lbwebserverport() != 80) {$IP .= ":".LoxBerry::System::lbwebserverport();}
 my $LBName = LoxBerry::System::lbfriendlyname() . " (" . LoxBerry::System::lbhostname() . ")";
 my $LBVer = LoxBerry::System::lbversion();
 our $msg1 = "NOTIFY * HTTP/1.1\r\nServer: $LBName $LBVer UPnP/1.0\r\nCache-Control: max-age=1800\r\nLOCATION: http://$IP/system/ssdpdesc.php\r\nNTS: ssdp:alive\r\nNT: upnp:rootdevice\r\nUSN: uuid:".$UUID."::upnp:rootdevice\r\nHOST: 239.255.255.250:1900\r\n\r\n";
 our $msg2 = "NOTIFY * HTTP/1.1\r\nServer: $LBName $LBVer UPnP/1.0\r\nCache-Control: max-age=1800\r\nLOCATION: http://$IP/system/ssdpdesc.php\r\nNTS: ssdp:alive\r\nNT: urn:schemas-upnp-org:device:HVAC_System:1\r\nUSN: uuid:".$UUID."::urn:schemas-upnp-org:device:HVAC_System:1\r\nHOST: 239.255.255.250:1900\r\n\r\n";
 my $msg3 = "HTTP/1.1 200 OK\r\nServer: %s %s UPnP/1.0\r\nCache-Control: max-age=1800\r\nEXT:\r\nDATE: %s\r\nLOCATION: http://%s/system/ssdpdesc.php\r\nST: upnp:rootdevice\r\nUSN: uuid:%s::upnp:rootdevice\r\n\r\n";
 my $msg4 = "HTTP/1.1 200 OK\r\nServer: %s %s UPnP/1.0\r\nCache-Control: max-age=1800\r\nEXT:\r\nDATE: %s\r\nLOCATION: http://%s/system/ssdpdesc.php\r\nST: urn:schemas-upnp-org:device:HVAC_System:1\r\nUSN: uuid:%s::urn:schemas-upnp-org:device:HVAC_System:1\r\n\r\n";
 my $msg5 = "HTTP/1.1 200 OK\r\nServer: %s %s UPnP/1.0\r\nCache-Control: max-age=1800\r\nEXT:\r\nDATE: %s\r\nLOCATION: http://%s/system/ssdpdesc.php\r\nST: uuid:%s\r\nUSN: uuid:%s::urn:schemas-upnp-org:device:HVAC_System:1\r\n\r\n";
 my $msg6 = "NOTIFY * HTTP/1.1\r\nServer: $LBName $LBVer UPnP/1.0\r\nCache-Control: max-age=1800\r\nLOCATION: http://$IP/system/ssdpdesc.php\r\nNTS: ssdp:byebye\r\nNT: upnp:rootdevice\r\nUSN: uuid:".$UUID."::upnp:rootdevice\r\nHOST: 239.255.255.250:1900\r\n\r\n";
 my $msg7 = "NOTIFY * HTTP/1.1\r\nServer: $LBName $LBVer UPnP/1.0\r\nCache-Control: max-age=1800\r\nLOCATION: http://$IP/system/ssdpdesc.php\r\nNTS: ssdp:byebye\r\nNT: urn:schemas-upnp-org:device:HVAC_System:1\r\nUSN: uuid:".$UUID."::urn:schemas-upnp-org:device:HVAC_System:1\r\nHOST: 239.255.255.250:1900\r\n\r\n";
 our $th = Thread->new(\&notify);

 my $tmp = "";
 my $buf = "";
 
 $SIG{INT} = \&signal_handler;
 $SIG{TERM} = \&signal_handler;
 $SIG{SIGTERM} = \&signal_handler;

 while(1) {
 	$s2->recv($buf,1024);
 	$from = $s2->peerhost();
 	$port = $s2->peerport();
 	if ( $buf =~ /^M-SEARCH/ && $buf =~ /ST:[ ]?upnp:rootdevice/) {
 		sleep 1;
 	  	$tmp = sprintf($msg3,$LBName,$LBVer,DateTime->now()->strftime("%a, %d %b %Y %H:%M:%S %z"),$IP,$UUID);
 	  	send($s1,$tmp,0,sockaddr_in($port,inet_aton($from)));
 	} elsif ($buf =~ /^M-SEARCH/ && $buf =~ /ST:[ ]?urn:schemas-upnp-org:device:HVAC_System:1/) {
 		sleep 1;
 		$tmp = sprintf($msg4,$LBName,$LBVer,DateTime->now()->strftime("%a, %d %b %Y %H:%M:%S %z"),$IP,$UUID);
 		send($s1,$tmp,0,sockaddr_in($port,inet_aton($from)));
 	} elsif ($buf =~ /^M-SEARCH/ && $buf =~ /ST:[ ]?uuid:$UUID/) {
 		sleep 1;
 		$tmp = sprintf($msg5,$LBName,$LBVer,DateTime->now()->strftime("%a, %d %b %Y %H:%M:%S %z"),$IP,$UUID,$UUID);
 		send($s1,$tmp,0,sockaddr_in($port,inet_aton($from)));
 	}
 }

 sub notify {
	 my $x =1;
	 while($x) {
		if ($x == 1) {
	 		$s2->mcast_send($msg1,'239.255.255.250:1900');
	 		$s2->mcast_send($msg2,'239.255.255.250:1900');
		} elsif ( $x == 1800 ) {
			$x = 0;
		}
		$x ++;
		$SIG{KILL} = sub { $x=0; };
		sleep 1;
	}
 }

 sub signal_handler {
	$s2->mcast_send($msg6,'239.255.255.250:1900');
	$s2->mcast_send($msg7,'239.255.255.250:1900');
	$th->kill('KILL')->join();
	exit 0;
 }
